/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WealthCreationRouteImport } from './routes/wealth-creation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VlogsIndexRouteImport } from './routes/vlogs.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VlogsSlugRouteImport } from './routes/vlogs.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WealthCreationRoute = WealthCreationRouteImport.update({
  id: '/wealth-creation',
  path: '/wealth-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VlogsIndexRoute = VlogsIndexRouteImport.update({
  id: '/vlogs/',
  path: '/vlogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VlogsSlugRoute = VlogsSlugRouteImport.update({
  id: '/vlogs/$slug',
  path: '/vlogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/wealth-creation': typeof WealthCreationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vlogs/$slug': typeof VlogsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vlogs/': typeof VlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/wealth-creation': typeof WealthCreationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vlogs/$slug': typeof VlogsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/vlogs': typeof VlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/wealth-creation': typeof WealthCreationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vlogs/$slug': typeof VlogsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/vlogs/': typeof VlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/wealth-creation'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/services/$slug'
    | '/vlogs/$slug'
    | '/blog/'
    | '/blogs/'
    | '/services/'
    | '/vlogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/wealth-creation'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/services/$slug'
    | '/vlogs/$slug'
    | '/blog'
    | '/blogs'
    | '/services'
    | '/vlogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/wealth-creation'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/services/$slug'
    | '/vlogs/$slug'
    | '/blog/'
    | '/blogs/'
    | '/services/'
    | '/vlogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  WealthCreationRoute: typeof WealthCreationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  VlogsSlugRoute: typeof VlogsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  VlogsIndexRoute: typeof VlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wealth-creation': {
      id: '/wealth-creation'
      path: '/wealth-creation'
      fullPath: '/wealth-creation'
      preLoaderRoute: typeof WealthCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vlogs/': {
      id: '/vlogs/'
      path: '/vlogs'
      fullPath: '/vlogs/'
      preLoaderRoute: typeof VlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vlogs/$slug': {
      id: '/vlogs/$slug'
      path: '/vlogs/$slug'
      fullPath: '/vlogs/$slug'
      preLoaderRoute: typeof VlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  WealthCreationRoute: WealthCreationRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  VlogsSlugRoute: VlogsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  VlogsIndexRoute: VlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
